### ISSUE TITLE
train関数の処理の実装

### ISSUE THREAD

**Issue by Geson-anko** [matsuo-group24-PinkTrombone/SpeechGeneration#52]
## 概要
`src/train.py`にある`train`関数の処理を実装します。

## 提案内容
実装したモデルの学習を開始するエントリーポイントを実装します。

## タスク
- [x] configs/train.yamlのdefaultsフィールドに次のように上記のファイルを追加  
    ```yaml
    defaults:
         - _self_
         - paths: default.yaml
         - hydra: default.yaml
         - env: make_env.yaml
         - model: dreamer.yaml
         - replay_buffer: replay_buffer.yaml
         - trainer: trainer.yaml
    ```
- [x] `python src/train.py`が実行できる
- [x] 学習が実行され、実験の記録が保存される。

## 参考
- [lightning-hydra-templateのsrc/train.py](https://github.com/ashleve/lightning-hydra-template/blob/main/src/train.py)
- [hydraの使い方について](https://github.com/matsuo-group24-PinkTrombone/SpeechGeneration/tree/main/configs#hydramain)
## 疑似コード

```py
def train(cfg: DictConfig) -> dict[str, float]:
    """Trains the model."""
    if cfg.get("seed") is not None:
        # reset seed.
    env = hydra.utils.instantiate(cfg.env)
    model = hydra.utils.instantiate(cfg.model)
    replay_buffer = hydra.utils.instantiate(cfg.replay_buffer)
    replay_buffer = replay_buffer(spaces=model.configure_replay_buffer_space(env))
    trainer = hydra.utils.instantiate(cfg.trainer)
    
    logger.info("Starting Training!")
    metric_dict = trainer.fit(env, replay_buffer, model)
    
    return metric_dict
````
